############################################################
# Dockerfile to build some-service-app container image
# Based on docker.dos.softlab.ru/rshb/efr/communication-systems/library/jboss-wildfly-10.1-cli
############################################################

# Use base wildfly 10.1.0 image as the base
FROM docker.dos.softlab.ru/rshb/efr/communication-systems/library/jboss-wildfly-10.1-cli

# Deploy app
ADD ./target/*.war /opt/jboss/wildfly/standalone/deployments/